# Generated by Django 2.0.2 on 2018-02-07 17:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Script'),
        ),
        migrations.AddField(
            model_name='score',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Track'),
        ),
    ]
