# Generated by Django 2.0.2 on 2018-02-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='Track 1', max_length=30),
            preserve_default=False,
        ),
    ]
