# Generated by Django 2.0.2 on 2018-02-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_track_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='trace',
            new_name='track',
        ),
    ]
