# Generated by Django 2.0.2 on 2018-02-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180207_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Script'),
        ),
    ]
