# Generated by Django 2.0.2 on 2018-02-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180207_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('runtime', models.CharField(max_length=30, unique=True)),
                ('help_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='script',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Language'),
            preserve_default=False,
        ),
    ]
