# Generated by Django 2.0.2 on 2018-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180214_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='ace_code',
            field=models.CharField(default='ace/mode/python', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='highlightjs_code',
            field=models.CharField(default='python', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='runtime',
            field=models.CharField(max_length=30),
        ),
    ]
