# Generated by Django 2.0.2 on 2018-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180214_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='help_text',
        ),
        migrations.AddField(
            model_name='language',
            name='help_text_file',
            field=models.CharField(default='python.html', max_length=30),
            preserve_default=False,
        ),
    ]
