# Generated by Django 2.0.2 on 2018-04-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_track_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='level',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
