# Generated by Django 2.0.2 on 2018-04-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180411_1127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('script', 'track')},
        ),
    ]
