# Generated by Django 2.0.4 on 2018-04-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180411_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Language'),
        ),
    ]
